language: cpp
sudo: false
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0 # clang 5.0
      - ubuntu-toolchain-r-test # gcc-6
    packages:
      - clang-5.0
      - g++-6
      - libsdl2-dev
before_install:
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "clang++" ]; then export CC=clang-5.0; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "clang++" ]; then export CXX=clang++-5.0; fi

  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "g++" ]; then export CC=gcc-6; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" = "g++" ]; then export CXX=g++-6; fi
script:
  - cmake $COMPONENT && make $TARGET
compiler:
  - clang
  - gcc
os:
  - linux
  #- osx
env:
  - COMPONENT=examples/minimal TARGET=minimal
  - COMPONENT=examples/ContainerHelloWorld TARGET=ContainerHelloWorld
  - COMPONENT=ntile TARGET=ntile
  - COMPONENT=tools/mapcompiler TARGET=mapcompiler

matrix:
  allow_failures:
    # GCC+ASAN on Travis is broken beyond repair
    #- compiler: gcc

    # OS X port hasn't been touched in years
    - os: osx
